language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- npm install -g react-native-cli
script:
- npm install
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_d5ba94eb55ce_key -iv $encrypted_d5ba94eb55ce_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
